### ISSUE TITLE
[REQ] Possible to use GSON instead of Jackson :)

### ISSUE THREAD

**Issue by klausmyrseth** [spincast/spincast-framework#2]
I noticed there is quite a bit side effects from using jackson compared to gson, I have much more control over the api and what it does when I use gson.

I would love to be able to configure my gson builder and inject it into spincast instead of jackson, perhaps as a plugin. Then I could clean out some dependencies from my project so its easier to support the new date classes and so on.

**Comment by electrotype** [comment]
Noted, thanks for the suggestion. I'll have a look into that when I can!

Also, feel free to contribute if you want/have time. https://www.spincast.org/community#contribution

**Comment by electrotype** [comment]
Gson support  added: [Spincast Gson plugin](https://www.spincast.org/plugins/spincast-gson)
